apiVersion: v1
kind: ConfigMap
metadata:
  name: vote-config
  namespace: voting-app
data:
  OPTION_A: "Pizza"
  OPTION_B: "Sushi"
  REDIS_HOST: "redis.voting-app.svc.cluster.local"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
  namespace: voting-app
data:
  REDIS_HOST: "redis.voting-app.svc.cluster.local"
  POSTGRES_HOST: "db.voting-app.svc.cluster.local"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: result-config
  namespace: voting-app
data:
  POSTGRES_HOST: "db.voting-app.svc.cluster.local"
